apiVersion: v1
kind: Service
metadata:
  name: my-database-api-service
  labels:
    app: my-database-api
spec:
  type: ClusterIP
  ports:
  - name: api-http
    protocol: TCP
    port: 8001
    targetPort: 8050
  - name: database
    protocol: TCP
    port: 8002
    targetPort: 3306 
  selector:
    app: my-database-api

